"""
Constants for image processing operations.
"""

# API timeouts (in seconds)
DANBOORU_TIMEOUT = 10
E621_TIMEOUT = 10
GELBOORU_TIMEOUT = 10
YANDERE_TIMEOUT = 10
PIXIV_TIMEOUT = 10
SAUCENAO_TIMEOUT = 20
PIXIV_DOWNLOAD_TIMEOUT = 30

# SauceNAO file size limits
SAUCENAO_MAX_SIZE_BYTES = 15 * 1024 * 1024  # 15MB
SAUCENAO_TARGET_SIZE_BYTES = 5 * 1024 * 1024  # 5MB target
SAUCENAO_MIN_QUALITY = 50
SAUCENAO_QUALITY_STEP = 10
SAUCENAO_INITIAL_QUALITY = 95
SAUCENAO_SIMILARITY_THRESHOLD = 80
SAUCENAO_NUM_RESULTS = 10

# Image processing thresholds
CHARACTER_THRESHOLD = 0.85
DEFAULT_TAGGER_THRESHOLD = 0.50
DEFAULT_STORAGE_THRESHOLD = 0.50

# Video processing
DEFAULT_VIDEO_FRAMES = 5

# File operations
MAX_COLLISION_ATTEMPTS = 50
BUCKET_CHARS = 3

# Tag pair processing
MAX_TAGS_FOR_PAIRS = 100  # Limit to prevent O(n²) explosion

# Progress reporting
SAUCENAO_STATS_REPORT_INTERVAL = 10  # Report stats every N requests
